#pragma once
#include "esphome/core/component.h"
#include "esphome/components/climate/climate.h"

namespace esphome {
namespace fancoil_climate {

class FancoilClimate : public climate::Climate, public Component {
 public:

  climate::ClimateTraits traits() override {
    auto t = climate::ClimateTraits();
    t.set_supports_current_temperature(true);
    t.set_supported_modes({
      climate::CLIMATE_MODE_OFF,
      climate::CLIMATE_MODE_COOL,
      climate::CLIMATE_MODE_HEAT,
      climate::CLIMATE_MODE_AUTO,
      climate::CLIMATE_MODE_FAN_ONLY,
    });
    t.set_supported_fan_modes({
      climate::CLIMATE_FAN_AUTO,
      climate::CLIMATE_FAN_LOW,
      climate::CLIMATE_FAN_MEDIUM,
      climate::CLIMATE_FAN_HIGH,
    });
    t.set_visual_min_temperature(16);
    t.set_visual_max_temperature(30);
    t.set_visual_temperature_step(0.5f);
    return t;
  }

  // Injected by climate.py via cg.add(var.set_control_callback(...)).
  // The lambda is generated by process_lambda with full id() access.
  void set_control_callback(std::function<void(climate::ClimateCall &)> cb) {
    control_cb_ = std::move(cb);
  }

  // Called from raw_* sensor on_value after a poll, when write lock is clear.
  void sync_from_globals(int sys, int op_mode, int fan, int sp_raw, float cur_temp) {
    current_temperature = cur_temp;
    target_temperature  = sp_raw / 10.0f;

    switch (fan) {
      case 1:  fan_mode = climate::CLIMATE_FAN_LOW;    break;
      case 2:  fan_mode = climate::CLIMATE_FAN_MEDIUM; break;
      case 3:  fan_mode = climate::CLIMATE_FAN_HIGH;   break;
      default: fan_mode = climate::CLIMATE_FAN_AUTO;   break;
    }

    if (sys == 0) {
      this->mode = climate::CLIMATE_MODE_OFF;
    } else if (sys == 1) {
      this->mode = climate::CLIMATE_MODE_FAN_ONLY;
    } else {
      switch (op_mode) {
        case 0:  this->mode = climate::CLIMATE_MODE_COOL; break;
        case 1:  this->mode = climate::CLIMATE_MODE_HEAT; break;
        default: this->mode = climate::CLIMATE_MODE_AUTO; break;
      }
    }
    publish_state();
  }

 protected:
  void control(const climate::ClimateCall &call) override {
    // Optimistic update — HA card reflects the change immediately.
    if (call.get_mode().has_value())
      this->mode = *call.get_mode();
    if (call.get_fan_mode().has_value())
      this->fan_mode = *call.get_fan_mode();
    if (call.get_target_temperature().has_value())
      this->target_temperature = *call.get_target_temperature();
    publish_state();

    // Run user logic: set write lock, update globals, queue FC16 write.
    if (control_cb_)
      control_cb_(const_cast<climate::ClimateCall &>(call));
  }

 private:
  std::function<void(climate::ClimateCall &)> control_cb_;
};

}  // namespace fancoil_climate
}  // namespace esphome
